// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqrqthncplrrpzniowat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcnF0aG5jcGxycnB6bmlvd2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTg1ODksImV4cCI6MjA2NzQ3NDU4OX0.z7L7Ch-FdvqjH5wxC-XEJU5x7E5AyeuMHM1KqkY1o2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});